questions = [
    ("How many humans  permanently live on Antarctica?"),
    ("How many moons does Earth have?"),
    ("How many World Wars have there been?"),
    ("How many classical orders of Greek architecture are there?"),
    ("How many dimensions does spacetime have in general relativity?"),
    ("How many Lagrange points exist in a two-body system?"),
    ("How many faces does a cube have?"),
    ("How many base units are there in the SI system?"),
    ("How many bits are in a byte?"),
    ("How many countries border Germany?"),
    ("How many decades are in a century?"),
    ("How many players are on the field for one soccer team?"),
    ("How many cranial nerves does a human have?"),
    ("How many stripes are there on the US flag?"),
    ("How many points are needed to win a game of snooker?"),
    ("How many books are there in the Old Testament (Protestant canon)?"),
    ("How many ounces are in a pound?"),
    ("How many syllables are there in a haiku?"),
    ("How many holes are there in a standard round of golf?"),
    ("How many years is a Metonic cycle?"),
    ("How many amino acids are used in standard protein synthesis?"),
]
